# -*- coding: utf-8 -*-
"""Aniket Tewari - ETG Summer Olympics Assignment Solution.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UTrgo1lsD5u3WzEqnhCj9auM893RwFGq

Summer  Olympics Data Analysis Assignment
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("summer.csv")

"""*1. In  how many cities Summer Olympics is held so far?*"""

a=len(pd.unique(df['City']))
print("The No. of Cities in which the Summer Olympics is held so far is= \n")
print(a)



"""*2. Which sport is having most number of Gold Medals so far? (Top 5)*"""

#Printing only Top Sports Name

b=df['Sport'][df['Medal'] =="Gold"].value_counts()
print("The Required Sport with most no. of Gold Medals is= \n")
b.nlargest(1)

#Printing Top 5 Sports Name and as well as plotting Bar Graph

b=df['Sport'][df['Medal'] =="Gold"].value_counts()
print("The Required Sport with most no. of Gold Medals is= \n")
b.nlargest(5)

#Printing Top 5 Sports Name and as well as plotting Bar Graph

b=df['Sport'][df['Medal'] =="Gold"].value_counts()
b.nlargest(5).plot.bar()
plt.xlabel('Name of the Athlete')
plt.ylabel('No. Of Gold Medals Won')
plt.title('Graph drawn by Aniket Tewari')



"""*3. Which sport is having most number of medals so far? (Top 5)*"""

#Printing only Top Sports Name

c=(df['Sport'][df['Medal']=="Gold"].value_counts()) + (df['Sport'][df['Medal']=="Silver"].value_counts()) + (df['Sport'][df['Medal']=="Bronze"].value_counts())
print("The Required Sport with most no. of Medals is= \n")
c.nlargest(1)

#Printing Top 5 Sports Name and as well as plotting Bar Graph

c=(df['Sport'][df['Medal']=="Gold"].value_counts()) + (df['Sport'][df['Medal']=="Silver"].value_counts()) + (df['Sport'][df['Medal']=="Bronze"].value_counts())
print("The Required Sport with most no. of Medals is= \n")
c.nlargest(5)

#Printing Top 5 Sports Name and as well as plotting Bar Graph

c=(df['Sport'][df['Medal']=="Gold"].value_counts()) + (df['Sport'][df['Medal']=="Silver"].value_counts()) + (df['Sport'][df['Medal']=="Bronze"].value_counts())
c.nlargest(5).plot.bar() 
plt.xlabel('Name of the Athlete')
plt.ylabel('No. Of Medals Won')
plt.title('Graph drawn by Aniket Tewari')



"""*4. Which player has won most number of medals? (Top 5)*"""

#Printing only Top Athlete Name

d=(df['Athlete'][df['Medal'] =="Gold"].value_counts()) + (df['Athlete'][df['Medal'] =="Silver"].value_counts()) + (df['Athlete'][df['Medal'] =="Bronze"].value_counts())
print("The Required Athlete with most no. of Medals is= \n")
d.nlargest(1)

#Printing Top 5 Athlete Names and as well as plotting Bar Graph

d=(df['Athlete'][df['Medal'] =="Gold"].value_counts()) + (df['Athlete'][df['Medal'] =="Silver"].value_counts()) + (df['Athlete'][df['Medal'] =="Bronze"].value_counts())
print("The Required Athlete with most no. of Medals is= \n")
d.nlargest(5)

#Printing Top 5 Athlete Names and as well as plotting Bar Graph

d=(df['Athlete'][df['Medal'] =="Gold"].value_counts()) + (df['Athlete'][df['Medal'] =="Silver"].value_counts()) + (df['Athlete'][df['Medal'] =="Bronze"].value_counts())
d.nlargest(5).plot.bar() 
plt.xlabel('Name of the Athlete')
plt.ylabel('No. of Medals Won')
plt.title('Graph drawn by Aniket Tewari')



"""*5. Which player has won most number Gold Medals of medals? (Top 5)*"""

#Printing only Top Athlete Name

e=df['Athlete'][df['Medal'] =="Gold"].value_counts()
print("The Required Athlete with most no. of Gold Medals is= \n")
e.nlargest(1)

#Printing Top 5 Athlete Names and as well as plotting Bar Graph

e=df['Athlete'][df['Medal'] =="Gold"].value_counts() 
print("The Required Athlete with most no. of Gold Medals is= \n")
e.nlargest(5)

#Printing Top 5 Athlete Names and as well as plotting Bar Graph

e=df['Athlete'][df['Medal'] =="Gold"].value_counts()
e.nlargest(5).plot.bar() 
plt.xlabel('Name of the Athlete')
plt.ylabel('No. of Gold Medals Won')
plt.title('Graph drawn by Aniket Tewari')



"""*6. In which year India won first Gold Medal in Summer Olympics?*"""

f=df[df['Country']=='IND'][df['Medal'] =='Gold'].index.values
print("The Required Year in which India won the First Gold Medal is= \n")
df.iloc[f[0]:f[0]+1,0:1]

#Another Result / Way

f=df[df['Country']=='IND'][df['Medal'] =='Gold'].index.values
print("The Required Year in which India won the First Gold Medal is= \n")
df[f[0]:f[0]+1]





"""*7. Which event is most popular in terms on number of players? (Top 5)*"""

#Printing values and graph for Top Sports in terms of most no. of Players

g=df['Sport'].value_counts()
print("The Sport which is popular in terms of most no. of Players is= \n") 
g.nlargest(1)

#Printing values and graph for Top 5 Sports in terms of most no. of Players

g=df['Sport'].value_counts()
print("The Sport which is popular in terms of most no. of Players is= \n") 
g.nlargest(5)

#Plotting graph for Top 5 Sports in terms of most no. of Players

g=df['Sport'].value_counts()
g.nlargest(5).plot.bar()
plt.xlabel('Name of the Sports')
plt.ylabel('No. of Players')
plt.title('Graph drawn by Aniket Tewari')



"""*8. Which sport is having most female Gold Medalists? (Top 5)*"""

#Printing values of Sports of Top Women Gold Medalists and plotting Bar Graph as well. 

h=df['Sport'][df['Medal'] =="Gold"][df['Gender']=="Women"].value_counts()
print("The Sports which is having most no. of Female Gold Medalists is= \n") 
h.nlargest(1)

#Printing values of Sports of Top 5 Women Gold Medalists and plotting Bar Graph as well. 

h=df['Sport'][df['Medal'] =="Gold"][df['Gender']=="Women"].value_counts()
print("The Sports which is having most no. of Female Gold Medalists is= \n") 
h.nlargest(5)

#Printing values of Top 5 Women Gold Medalists and plotting Bar Graph as well. 

h=df['Sport'][df['Medal'] =="Gold"][df['Gender']=="Women"].value_counts()
print("The Sports which is having most no. of Female Gold Medalists is= \n") 
h.nlargest(5).plot.bar()
plt.xlabel('Name of the Sports')
plt.ylabel('No. of Female Gold Medalists')
plt.title('Graph drawn by Aniket Tewari')

